version: '3'

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    environment:
      POSTGRES_DB: nn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0p9o8i
    ports:
      - '5432:5432'
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:0p9o8i@db:5432/nn?schema=custom